name: "Build and deploy to VM"
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Dist files
        run: |
          yarn install
          yarn build

      - id: auth
        name: Authenticate GCP
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: ${{ secrets.GCP_KEYS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Remove Existing Build Files
        run: |
          gcloud compute ssh --zone ${{secrets.VM_ZONE}} ${{secrets.VM_INSTANCE}}  --project ${{secrets.PROJECT_ID}} --command "rm -rf /var/www/backend-stats/frontend/dist/"

      - name: Copy files to VM
        run: |
          gcloud compute scp  --recurse --project ${{secrets.PROJECT_ID}} --zone ${{secrets.VM_ZONE}} ./dist ${{secrets.VM_INSTANCE}}:/var/www/backend-stats/frontend/dist

      - name: Restart Nginx
        run: |
          gcloud compute ssh --zone ${{secrets.VM_ZONE}} ${{secrets.VM_INSTANCE}}  --project ${{secrets.PROJECT_ID}} --command "
          systemctl restart nginx && systemctl status nginx"
